/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as GmailCallbackRouteImport } from './routes/gmail-callback'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTodosListRouteImport } from './routes/_authenticated/todos-list'
import { Route as AuthenticatedTodosRouteImport } from './routes/_authenticated/todos'
import { Route as AuthenticatedTodayPlanRouteImport } from './routes/_authenticated/today-plan'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReflectRouteImport } from './routes/_authenticated/reflect'
import { Route as AuthenticatedPeopleRouteImport } from './routes/_authenticated/people'
import { Route as AuthenticatedNotesRouteImport } from './routes/_authenticated/notes'
import { Route as AuthenticatedInboxRouteImport } from './routes/_authenticated/inbox'
import { Route as AuthenticatedFocusRouteImport } from './routes/_authenticated/focus'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedTodosIndexRouteImport } from './routes/_authenticated/todos/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedReflectIndexRouteImport } from './routes/_authenticated/reflect/index'
import { Route as AuthenticatedPeopleIndexRouteImport } from './routes/_authenticated/people/index'
import { Route as AuthenticatedNotesIndexRouteImport } from './routes/_authenticated/notes/index'
import { Route as AuthenticatedTodosDocumentIdRouteImport } from './routes/_authenticated/todos/$documentId'
import { Route as AuthenticatedSettingsSampleOutputsRouteImport } from './routes/_authenticated/settings/sample-outputs'
import { Route as AuthenticatedSettingsPromptsRouteImport } from './routes/_authenticated/settings/prompts'
import { Route as AuthenticatedSettingsProjectsRouteImport } from './routes/_authenticated/settings/projects'
import { Route as AuthenticatedSettingsLocationsRouteImport } from './routes/_authenticated/settings/locations'
import { Route as AuthenticatedSettingsLinearRouteImport } from './routes/_authenticated/settings/linear'
import { Route as AuthenticatedSettingsIntegrationsRouteImport } from './routes/_authenticated/settings/integrations'
import { Route as AuthenticatedSettingsHubstaffRouteImport } from './routes/_authenticated/settings/hubstaff'
import { Route as AuthenticatedSettingsGmailRouteImport } from './routes/_authenticated/settings/gmail'
import { Route as AuthenticatedSettingsCalendarRouteImport } from './routes/_authenticated/settings/calendar'
import { Route as AuthenticatedSettingsAiCostsRouteImport } from './routes/_authenticated/settings/ai-costs'
import { Route as AuthenticatedSettingsAiRouteImport } from './routes/_authenticated/settings/ai'
import { Route as AuthenticatedPeopleDatingRouteImport } from './routes/_authenticated/people/dating'
import { Route as AuthenticatedPeopleContactIdRouteImport } from './routes/_authenticated/people/$contactId'
import { Route as AuthenticatedNotesDocumentIdRouteImport } from './routes/_authenticated/notes/$documentId'
import { Route as AuthenticatedReflectStatsIndexRouteImport } from './routes/_authenticated/reflect/stats/index'
import { Route as AuthenticatedSettingsProjectsProjectIdRouteImport } from './routes/_authenticated/settings/projects.$projectId'
import { Route as AuthenticatedReflectStatsMessagesRouteImport } from './routes/_authenticated/reflect/stats/messages'
import { Route as AuthenticatedReflectStatsLinearRouteImport } from './routes/_authenticated/reflect/stats/linear'
import { Route as AuthenticatedReflectStatsHubstaffRouteImport } from './routes/_authenticated/reflect/stats/hubstaff'
import { Route as AuthenticatedReflectStatsGmailRouteImport } from './routes/_authenticated/reflect/stats/gmail'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const GmailCallbackRoute = GmailCallbackRouteImport.update({
  id: '/gmail-callback',
  path: '/gmail-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTodosListRoute = AuthenticatedTodosListRouteImport.update({
  id: '/todos-list',
  path: '/todos-list',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTodosRoute = AuthenticatedTodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTodayPlanRoute = AuthenticatedTodayPlanRouteImport.update({
  id: '/today-plan',
  path: '/today-plan',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReflectRoute = AuthenticatedReflectRouteImport.update({
  id: '/reflect',
  path: '/reflect',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPeopleRoute = AuthenticatedPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotesRoute = AuthenticatedNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInboxRoute = AuthenticatedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFocusRoute = AuthenticatedFocusRouteImport.update({
  id: '/focus',
  path: '/focus',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTodosIndexRoute = AuthenticatedTodosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedTodosRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedReflectIndexRoute =
  AuthenticatedReflectIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedReflectRoute,
  } as any)
const AuthenticatedPeopleIndexRoute =
  AuthenticatedPeopleIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPeopleRoute,
  } as any)
const AuthenticatedNotesIndexRoute = AuthenticatedNotesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedNotesRoute,
} as any)
const AuthenticatedTodosDocumentIdRoute =
  AuthenticatedTodosDocumentIdRouteImport.update({
    id: '/$documentId',
    path: '/$documentId',
    getParentRoute: () => AuthenticatedTodosRoute,
  } as any)
const AuthenticatedSettingsSampleOutputsRoute =
  AuthenticatedSettingsSampleOutputsRouteImport.update({
    id: '/sample-outputs',
    path: '/sample-outputs',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsPromptsRoute =
  AuthenticatedSettingsPromptsRouteImport.update({
    id: '/prompts',
    path: '/prompts',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsProjectsRoute =
  AuthenticatedSettingsProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsLocationsRoute =
  AuthenticatedSettingsLocationsRouteImport.update({
    id: '/locations',
    path: '/locations',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsLinearRoute =
  AuthenticatedSettingsLinearRouteImport.update({
    id: '/linear',
    path: '/linear',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsIntegrationsRoute =
  AuthenticatedSettingsIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsHubstaffRoute =
  AuthenticatedSettingsHubstaffRouteImport.update({
    id: '/hubstaff',
    path: '/hubstaff',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsGmailRoute =
  AuthenticatedSettingsGmailRouteImport.update({
    id: '/gmail',
    path: '/gmail',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsCalendarRoute =
  AuthenticatedSettingsCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsAiCostsRoute =
  AuthenticatedSettingsAiCostsRouteImport.update({
    id: '/ai-costs',
    path: '/ai-costs',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsAiRoute = AuthenticatedSettingsAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedSettingsRoute,
} as any)
const AuthenticatedPeopleDatingRoute =
  AuthenticatedPeopleDatingRouteImport.update({
    id: '/dating',
    path: '/dating',
    getParentRoute: () => AuthenticatedPeopleRoute,
  } as any)
const AuthenticatedPeopleContactIdRoute =
  AuthenticatedPeopleContactIdRouteImport.update({
    id: '/$contactId',
    path: '/$contactId',
    getParentRoute: () => AuthenticatedPeopleRoute,
  } as any)
const AuthenticatedNotesDocumentIdRoute =
  AuthenticatedNotesDocumentIdRouteImport.update({
    id: '/$documentId',
    path: '/$documentId',
    getParentRoute: () => AuthenticatedNotesRoute,
  } as any)
const AuthenticatedReflectStatsIndexRoute =
  AuthenticatedReflectStatsIndexRouteImport.update({
    id: '/stats/',
    path: '/stats/',
    getParentRoute: () => AuthenticatedReflectRoute,
  } as any)
const AuthenticatedSettingsProjectsProjectIdRoute =
  AuthenticatedSettingsProjectsProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => AuthenticatedSettingsProjectsRoute,
  } as any)
const AuthenticatedReflectStatsMessagesRoute =
  AuthenticatedReflectStatsMessagesRouteImport.update({
    id: '/stats/messages',
    path: '/stats/messages',
    getParentRoute: () => AuthenticatedReflectRoute,
  } as any)
const AuthenticatedReflectStatsLinearRoute =
  AuthenticatedReflectStatsLinearRouteImport.update({
    id: '/stats/linear',
    path: '/stats/linear',
    getParentRoute: () => AuthenticatedReflectRoute,
  } as any)
const AuthenticatedReflectStatsHubstaffRoute =
  AuthenticatedReflectStatsHubstaffRouteImport.update({
    id: '/stats/hubstaff',
    path: '/stats/hubstaff',
    getParentRoute: () => AuthenticatedReflectRoute,
  } as any)
const AuthenticatedReflectStatsGmailRoute =
  AuthenticatedReflectStatsGmailRouteImport.update({
    id: '/stats/gmail',
    path: '/stats/gmail',
    getParentRoute: () => AuthenticatedReflectRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/gmail-callback': typeof GmailCallbackRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/chat': typeof AuthenticatedChatRoute
  '/focus': typeof AuthenticatedFocusRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/notes': typeof AuthenticatedNotesRouteWithChildren
  '/people': typeof AuthenticatedPeopleRouteWithChildren
  '/reflect': typeof AuthenticatedReflectRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/today-plan': typeof AuthenticatedTodayPlanRoute
  '/todos': typeof AuthenticatedTodosRouteWithChildren
  '/todos-list': typeof AuthenticatedTodosListRoute
  '/': typeof AuthenticatedIndexRoute
  '/notes/$documentId': typeof AuthenticatedNotesDocumentIdRoute
  '/people/$contactId': typeof AuthenticatedPeopleContactIdRoute
  '/people/dating': typeof AuthenticatedPeopleDatingRoute
  '/settings/ai': typeof AuthenticatedSettingsAiRoute
  '/settings/ai-costs': typeof AuthenticatedSettingsAiCostsRoute
  '/settings/calendar': typeof AuthenticatedSettingsCalendarRoute
  '/settings/gmail': typeof AuthenticatedSettingsGmailRoute
  '/settings/hubstaff': typeof AuthenticatedSettingsHubstaffRoute
  '/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/settings/linear': typeof AuthenticatedSettingsLinearRoute
  '/settings/locations': typeof AuthenticatedSettingsLocationsRoute
  '/settings/projects': typeof AuthenticatedSettingsProjectsRouteWithChildren
  '/settings/prompts': typeof AuthenticatedSettingsPromptsRoute
  '/settings/sample-outputs': typeof AuthenticatedSettingsSampleOutputsRoute
  '/todos/$documentId': typeof AuthenticatedTodosDocumentIdRoute
  '/notes/': typeof AuthenticatedNotesIndexRoute
  '/people/': typeof AuthenticatedPeopleIndexRoute
  '/reflect/': typeof AuthenticatedReflectIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/todos/': typeof AuthenticatedTodosIndexRoute
  '/reflect/stats/gmail': typeof AuthenticatedReflectStatsGmailRoute
  '/reflect/stats/hubstaff': typeof AuthenticatedReflectStatsHubstaffRoute
  '/reflect/stats/linear': typeof AuthenticatedReflectStatsLinearRoute
  '/reflect/stats/messages': typeof AuthenticatedReflectStatsMessagesRoute
  '/settings/projects/$projectId': typeof AuthenticatedSettingsProjectsProjectIdRoute
  '/reflect/stats': typeof AuthenticatedReflectStatsIndexRoute
}
export interface FileRoutesByTo {
  '/gmail-callback': typeof GmailCallbackRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/chat': typeof AuthenticatedChatRoute
  '/focus': typeof AuthenticatedFocusRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/today-plan': typeof AuthenticatedTodayPlanRoute
  '/todos-list': typeof AuthenticatedTodosListRoute
  '/': typeof AuthenticatedIndexRoute
  '/notes/$documentId': typeof AuthenticatedNotesDocumentIdRoute
  '/people/$contactId': typeof AuthenticatedPeopleContactIdRoute
  '/people/dating': typeof AuthenticatedPeopleDatingRoute
  '/settings/ai': typeof AuthenticatedSettingsAiRoute
  '/settings/ai-costs': typeof AuthenticatedSettingsAiCostsRoute
  '/settings/calendar': typeof AuthenticatedSettingsCalendarRoute
  '/settings/gmail': typeof AuthenticatedSettingsGmailRoute
  '/settings/hubstaff': typeof AuthenticatedSettingsHubstaffRoute
  '/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/settings/linear': typeof AuthenticatedSettingsLinearRoute
  '/settings/locations': typeof AuthenticatedSettingsLocationsRoute
  '/settings/projects': typeof AuthenticatedSettingsProjectsRouteWithChildren
  '/settings/prompts': typeof AuthenticatedSettingsPromptsRoute
  '/settings/sample-outputs': typeof AuthenticatedSettingsSampleOutputsRoute
  '/todos/$documentId': typeof AuthenticatedTodosDocumentIdRoute
  '/notes': typeof AuthenticatedNotesIndexRoute
  '/people': typeof AuthenticatedPeopleIndexRoute
  '/reflect': typeof AuthenticatedReflectIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/todos': typeof AuthenticatedTodosIndexRoute
  '/reflect/stats/gmail': typeof AuthenticatedReflectStatsGmailRoute
  '/reflect/stats/hubstaff': typeof AuthenticatedReflectStatsHubstaffRoute
  '/reflect/stats/linear': typeof AuthenticatedReflectStatsLinearRoute
  '/reflect/stats/messages': typeof AuthenticatedReflectStatsMessagesRoute
  '/settings/projects/$projectId': typeof AuthenticatedSettingsProjectsProjectIdRoute
  '/reflect/stats': typeof AuthenticatedReflectStatsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/gmail-callback': typeof GmailCallbackRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/focus': typeof AuthenticatedFocusRoute
  '/_authenticated/inbox': typeof AuthenticatedInboxRoute
  '/_authenticated/notes': typeof AuthenticatedNotesRouteWithChildren
  '/_authenticated/people': typeof AuthenticatedPeopleRouteWithChildren
  '/_authenticated/reflect': typeof AuthenticatedReflectRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/today-plan': typeof AuthenticatedTodayPlanRoute
  '/_authenticated/todos': typeof AuthenticatedTodosRouteWithChildren
  '/_authenticated/todos-list': typeof AuthenticatedTodosListRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/notes/$documentId': typeof AuthenticatedNotesDocumentIdRoute
  '/_authenticated/people/$contactId': typeof AuthenticatedPeopleContactIdRoute
  '/_authenticated/people/dating': typeof AuthenticatedPeopleDatingRoute
  '/_authenticated/settings/ai': typeof AuthenticatedSettingsAiRoute
  '/_authenticated/settings/ai-costs': typeof AuthenticatedSettingsAiCostsRoute
  '/_authenticated/settings/calendar': typeof AuthenticatedSettingsCalendarRoute
  '/_authenticated/settings/gmail': typeof AuthenticatedSettingsGmailRoute
  '/_authenticated/settings/hubstaff': typeof AuthenticatedSettingsHubstaffRoute
  '/_authenticated/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/_authenticated/settings/linear': typeof AuthenticatedSettingsLinearRoute
  '/_authenticated/settings/locations': typeof AuthenticatedSettingsLocationsRoute
  '/_authenticated/settings/projects': typeof AuthenticatedSettingsProjectsRouteWithChildren
  '/_authenticated/settings/prompts': typeof AuthenticatedSettingsPromptsRoute
  '/_authenticated/settings/sample-outputs': typeof AuthenticatedSettingsSampleOutputsRoute
  '/_authenticated/todos/$documentId': typeof AuthenticatedTodosDocumentIdRoute
  '/_authenticated/notes/': typeof AuthenticatedNotesIndexRoute
  '/_authenticated/people/': typeof AuthenticatedPeopleIndexRoute
  '/_authenticated/reflect/': typeof AuthenticatedReflectIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/todos/': typeof AuthenticatedTodosIndexRoute
  '/_authenticated/reflect/stats/gmail': typeof AuthenticatedReflectStatsGmailRoute
  '/_authenticated/reflect/stats/hubstaff': typeof AuthenticatedReflectStatsHubstaffRoute
  '/_authenticated/reflect/stats/linear': typeof AuthenticatedReflectStatsLinearRoute
  '/_authenticated/reflect/stats/messages': typeof AuthenticatedReflectStatsMessagesRoute
  '/_authenticated/settings/projects/$projectId': typeof AuthenticatedSettingsProjectsProjectIdRoute
  '/_authenticated/reflect/stats/': typeof AuthenticatedReflectStatsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/gmail-callback'
    | '/sign-in'
    | '/sign-up'
    | '/chat'
    | '/focus'
    | '/inbox'
    | '/notes'
    | '/people'
    | '/reflect'
    | '/settings'
    | '/today-plan'
    | '/todos'
    | '/todos-list'
    | '/'
    | '/notes/$documentId'
    | '/people/$contactId'
    | '/people/dating'
    | '/settings/ai'
    | '/settings/ai-costs'
    | '/settings/calendar'
    | '/settings/gmail'
    | '/settings/hubstaff'
    | '/settings/integrations'
    | '/settings/linear'
    | '/settings/locations'
    | '/settings/projects'
    | '/settings/prompts'
    | '/settings/sample-outputs'
    | '/todos/$documentId'
    | '/notes/'
    | '/people/'
    | '/reflect/'
    | '/settings/'
    | '/todos/'
    | '/reflect/stats/gmail'
    | '/reflect/stats/hubstaff'
    | '/reflect/stats/linear'
    | '/reflect/stats/messages'
    | '/settings/projects/$projectId'
    | '/reflect/stats'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/gmail-callback'
    | '/sign-in'
    | '/sign-up'
    | '/chat'
    | '/focus'
    | '/inbox'
    | '/today-plan'
    | '/todos-list'
    | '/'
    | '/notes/$documentId'
    | '/people/$contactId'
    | '/people/dating'
    | '/settings/ai'
    | '/settings/ai-costs'
    | '/settings/calendar'
    | '/settings/gmail'
    | '/settings/hubstaff'
    | '/settings/integrations'
    | '/settings/linear'
    | '/settings/locations'
    | '/settings/projects'
    | '/settings/prompts'
    | '/settings/sample-outputs'
    | '/todos/$documentId'
    | '/notes'
    | '/people'
    | '/reflect'
    | '/settings'
    | '/todos'
    | '/reflect/stats/gmail'
    | '/reflect/stats/hubstaff'
    | '/reflect/stats/linear'
    | '/reflect/stats/messages'
    | '/settings/projects/$projectId'
    | '/reflect/stats'
  id:
    | '__root__'
    | '/_authenticated'
    | '/gmail-callback'
    | '/sign-in'
    | '/sign-up'
    | '/_authenticated/chat'
    | '/_authenticated/focus'
    | '/_authenticated/inbox'
    | '/_authenticated/notes'
    | '/_authenticated/people'
    | '/_authenticated/reflect'
    | '/_authenticated/settings'
    | '/_authenticated/today-plan'
    | '/_authenticated/todos'
    | '/_authenticated/todos-list'
    | '/_authenticated/'
    | '/_authenticated/notes/$documentId'
    | '/_authenticated/people/$contactId'
    | '/_authenticated/people/dating'
    | '/_authenticated/settings/ai'
    | '/_authenticated/settings/ai-costs'
    | '/_authenticated/settings/calendar'
    | '/_authenticated/settings/gmail'
    | '/_authenticated/settings/hubstaff'
    | '/_authenticated/settings/integrations'
    | '/_authenticated/settings/linear'
    | '/_authenticated/settings/locations'
    | '/_authenticated/settings/projects'
    | '/_authenticated/settings/prompts'
    | '/_authenticated/settings/sample-outputs'
    | '/_authenticated/todos/$documentId'
    | '/_authenticated/notes/'
    | '/_authenticated/people/'
    | '/_authenticated/reflect/'
    | '/_authenticated/settings/'
    | '/_authenticated/todos/'
    | '/_authenticated/reflect/stats/gmail'
    | '/_authenticated/reflect/stats/hubstaff'
    | '/_authenticated/reflect/stats/linear'
    | '/_authenticated/reflect/stats/messages'
    | '/_authenticated/settings/projects/$projectId'
    | '/_authenticated/reflect/stats/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  GmailCallbackRoute: typeof GmailCallbackRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gmail-callback': {
      id: '/gmail-callback'
      path: '/gmail-callback'
      fullPath: '/gmail-callback'
      preLoaderRoute: typeof GmailCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/todos-list': {
      id: '/_authenticated/todos-list'
      path: '/todos-list'
      fullPath: '/todos-list'
      preLoaderRoute: typeof AuthenticatedTodosListRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/todos': {
      id: '/_authenticated/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof AuthenticatedTodosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/today-plan': {
      id: '/_authenticated/today-plan'
      path: '/today-plan'
      fullPath: '/today-plan'
      preLoaderRoute: typeof AuthenticatedTodayPlanRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reflect': {
      id: '/_authenticated/reflect'
      path: '/reflect'
      fullPath: '/reflect'
      preLoaderRoute: typeof AuthenticatedReflectRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/people': {
      id: '/_authenticated/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof AuthenticatedPeopleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notes': {
      id: '/_authenticated/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AuthenticatedNotesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inbox': {
      id: '/_authenticated/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedInboxRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/focus': {
      id: '/_authenticated/focus'
      path: '/focus'
      fullPath: '/focus'
      preLoaderRoute: typeof AuthenticatedFocusRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/todos/': {
      id: '/_authenticated/todos/'
      path: '/'
      fullPath: '/todos/'
      preLoaderRoute: typeof AuthenticatedTodosIndexRouteImport
      parentRoute: typeof AuthenticatedTodosRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/reflect/': {
      id: '/_authenticated/reflect/'
      path: '/'
      fullPath: '/reflect/'
      preLoaderRoute: typeof AuthenticatedReflectIndexRouteImport
      parentRoute: typeof AuthenticatedReflectRoute
    }
    '/_authenticated/people/': {
      id: '/_authenticated/people/'
      path: '/'
      fullPath: '/people/'
      preLoaderRoute: typeof AuthenticatedPeopleIndexRouteImport
      parentRoute: typeof AuthenticatedPeopleRoute
    }
    '/_authenticated/notes/': {
      id: '/_authenticated/notes/'
      path: '/'
      fullPath: '/notes/'
      preLoaderRoute: typeof AuthenticatedNotesIndexRouteImport
      parentRoute: typeof AuthenticatedNotesRoute
    }
    '/_authenticated/todos/$documentId': {
      id: '/_authenticated/todos/$documentId'
      path: '/$documentId'
      fullPath: '/todos/$documentId'
      preLoaderRoute: typeof AuthenticatedTodosDocumentIdRouteImport
      parentRoute: typeof AuthenticatedTodosRoute
    }
    '/_authenticated/settings/sample-outputs': {
      id: '/_authenticated/settings/sample-outputs'
      path: '/sample-outputs'
      fullPath: '/settings/sample-outputs'
      preLoaderRoute: typeof AuthenticatedSettingsSampleOutputsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/prompts': {
      id: '/_authenticated/settings/prompts'
      path: '/prompts'
      fullPath: '/settings/prompts'
      preLoaderRoute: typeof AuthenticatedSettingsPromptsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/projects': {
      id: '/_authenticated/settings/projects'
      path: '/projects'
      fullPath: '/settings/projects'
      preLoaderRoute: typeof AuthenticatedSettingsProjectsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/locations': {
      id: '/_authenticated/settings/locations'
      path: '/locations'
      fullPath: '/settings/locations'
      preLoaderRoute: typeof AuthenticatedSettingsLocationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/linear': {
      id: '/_authenticated/settings/linear'
      path: '/linear'
      fullPath: '/settings/linear'
      preLoaderRoute: typeof AuthenticatedSettingsLinearRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/integrations': {
      id: '/_authenticated/settings/integrations'
      path: '/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof AuthenticatedSettingsIntegrationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/hubstaff': {
      id: '/_authenticated/settings/hubstaff'
      path: '/hubstaff'
      fullPath: '/settings/hubstaff'
      preLoaderRoute: typeof AuthenticatedSettingsHubstaffRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/gmail': {
      id: '/_authenticated/settings/gmail'
      path: '/gmail'
      fullPath: '/settings/gmail'
      preLoaderRoute: typeof AuthenticatedSettingsGmailRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/calendar': {
      id: '/_authenticated/settings/calendar'
      path: '/calendar'
      fullPath: '/settings/calendar'
      preLoaderRoute: typeof AuthenticatedSettingsCalendarRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/ai-costs': {
      id: '/_authenticated/settings/ai-costs'
      path: '/ai-costs'
      fullPath: '/settings/ai-costs'
      preLoaderRoute: typeof AuthenticatedSettingsAiCostsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/ai': {
      id: '/_authenticated/settings/ai'
      path: '/ai'
      fullPath: '/settings/ai'
      preLoaderRoute: typeof AuthenticatedSettingsAiRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/people/dating': {
      id: '/_authenticated/people/dating'
      path: '/dating'
      fullPath: '/people/dating'
      preLoaderRoute: typeof AuthenticatedPeopleDatingRouteImport
      parentRoute: typeof AuthenticatedPeopleRoute
    }
    '/_authenticated/people/$contactId': {
      id: '/_authenticated/people/$contactId'
      path: '/$contactId'
      fullPath: '/people/$contactId'
      preLoaderRoute: typeof AuthenticatedPeopleContactIdRouteImport
      parentRoute: typeof AuthenticatedPeopleRoute
    }
    '/_authenticated/notes/$documentId': {
      id: '/_authenticated/notes/$documentId'
      path: '/$documentId'
      fullPath: '/notes/$documentId'
      preLoaderRoute: typeof AuthenticatedNotesDocumentIdRouteImport
      parentRoute: typeof AuthenticatedNotesRoute
    }
    '/_authenticated/reflect/stats/': {
      id: '/_authenticated/reflect/stats/'
      path: '/stats'
      fullPath: '/reflect/stats'
      preLoaderRoute: typeof AuthenticatedReflectStatsIndexRouteImport
      parentRoute: typeof AuthenticatedReflectRoute
    }
    '/_authenticated/settings/projects/$projectId': {
      id: '/_authenticated/settings/projects/$projectId'
      path: '/$projectId'
      fullPath: '/settings/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedSettingsProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedSettingsProjectsRoute
    }
    '/_authenticated/reflect/stats/messages': {
      id: '/_authenticated/reflect/stats/messages'
      path: '/stats/messages'
      fullPath: '/reflect/stats/messages'
      preLoaderRoute: typeof AuthenticatedReflectStatsMessagesRouteImport
      parentRoute: typeof AuthenticatedReflectRoute
    }
    '/_authenticated/reflect/stats/linear': {
      id: '/_authenticated/reflect/stats/linear'
      path: '/stats/linear'
      fullPath: '/reflect/stats/linear'
      preLoaderRoute: typeof AuthenticatedReflectStatsLinearRouteImport
      parentRoute: typeof AuthenticatedReflectRoute
    }
    '/_authenticated/reflect/stats/hubstaff': {
      id: '/_authenticated/reflect/stats/hubstaff'
      path: '/stats/hubstaff'
      fullPath: '/reflect/stats/hubstaff'
      preLoaderRoute: typeof AuthenticatedReflectStatsHubstaffRouteImport
      parentRoute: typeof AuthenticatedReflectRoute
    }
    '/_authenticated/reflect/stats/gmail': {
      id: '/_authenticated/reflect/stats/gmail'
      path: '/stats/gmail'
      fullPath: '/reflect/stats/gmail'
      preLoaderRoute: typeof AuthenticatedReflectStatsGmailRouteImport
      parentRoute: typeof AuthenticatedReflectRoute
    }
  }
}

interface AuthenticatedNotesRouteChildren {
  AuthenticatedNotesDocumentIdRoute: typeof AuthenticatedNotesDocumentIdRoute
  AuthenticatedNotesIndexRoute: typeof AuthenticatedNotesIndexRoute
}

const AuthenticatedNotesRouteChildren: AuthenticatedNotesRouteChildren = {
  AuthenticatedNotesDocumentIdRoute: AuthenticatedNotesDocumentIdRoute,
  AuthenticatedNotesIndexRoute: AuthenticatedNotesIndexRoute,
}

const AuthenticatedNotesRouteWithChildren =
  AuthenticatedNotesRoute._addFileChildren(AuthenticatedNotesRouteChildren)

interface AuthenticatedPeopleRouteChildren {
  AuthenticatedPeopleContactIdRoute: typeof AuthenticatedPeopleContactIdRoute
  AuthenticatedPeopleDatingRoute: typeof AuthenticatedPeopleDatingRoute
  AuthenticatedPeopleIndexRoute: typeof AuthenticatedPeopleIndexRoute
}

const AuthenticatedPeopleRouteChildren: AuthenticatedPeopleRouteChildren = {
  AuthenticatedPeopleContactIdRoute: AuthenticatedPeopleContactIdRoute,
  AuthenticatedPeopleDatingRoute: AuthenticatedPeopleDatingRoute,
  AuthenticatedPeopleIndexRoute: AuthenticatedPeopleIndexRoute,
}

const AuthenticatedPeopleRouteWithChildren =
  AuthenticatedPeopleRoute._addFileChildren(AuthenticatedPeopleRouteChildren)

interface AuthenticatedReflectRouteChildren {
  AuthenticatedReflectIndexRoute: typeof AuthenticatedReflectIndexRoute
  AuthenticatedReflectStatsGmailRoute: typeof AuthenticatedReflectStatsGmailRoute
  AuthenticatedReflectStatsHubstaffRoute: typeof AuthenticatedReflectStatsHubstaffRoute
  AuthenticatedReflectStatsLinearRoute: typeof AuthenticatedReflectStatsLinearRoute
  AuthenticatedReflectStatsMessagesRoute: typeof AuthenticatedReflectStatsMessagesRoute
  AuthenticatedReflectStatsIndexRoute: typeof AuthenticatedReflectStatsIndexRoute
}

const AuthenticatedReflectRouteChildren: AuthenticatedReflectRouteChildren = {
  AuthenticatedReflectIndexRoute: AuthenticatedReflectIndexRoute,
  AuthenticatedReflectStatsGmailRoute: AuthenticatedReflectStatsGmailRoute,
  AuthenticatedReflectStatsHubstaffRoute:
    AuthenticatedReflectStatsHubstaffRoute,
  AuthenticatedReflectStatsLinearRoute: AuthenticatedReflectStatsLinearRoute,
  AuthenticatedReflectStatsMessagesRoute:
    AuthenticatedReflectStatsMessagesRoute,
  AuthenticatedReflectStatsIndexRoute: AuthenticatedReflectStatsIndexRoute,
}

const AuthenticatedReflectRouteWithChildren =
  AuthenticatedReflectRoute._addFileChildren(AuthenticatedReflectRouteChildren)

interface AuthenticatedSettingsProjectsRouteChildren {
  AuthenticatedSettingsProjectsProjectIdRoute: typeof AuthenticatedSettingsProjectsProjectIdRoute
}

const AuthenticatedSettingsProjectsRouteChildren: AuthenticatedSettingsProjectsRouteChildren =
  {
    AuthenticatedSettingsProjectsProjectIdRoute:
      AuthenticatedSettingsProjectsProjectIdRoute,
  }

const AuthenticatedSettingsProjectsRouteWithChildren =
  AuthenticatedSettingsProjectsRoute._addFileChildren(
    AuthenticatedSettingsProjectsRouteChildren,
  )

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsAiRoute: typeof AuthenticatedSettingsAiRoute
  AuthenticatedSettingsAiCostsRoute: typeof AuthenticatedSettingsAiCostsRoute
  AuthenticatedSettingsCalendarRoute: typeof AuthenticatedSettingsCalendarRoute
  AuthenticatedSettingsGmailRoute: typeof AuthenticatedSettingsGmailRoute
  AuthenticatedSettingsHubstaffRoute: typeof AuthenticatedSettingsHubstaffRoute
  AuthenticatedSettingsIntegrationsRoute: typeof AuthenticatedSettingsIntegrationsRoute
  AuthenticatedSettingsLinearRoute: typeof AuthenticatedSettingsLinearRoute
  AuthenticatedSettingsLocationsRoute: typeof AuthenticatedSettingsLocationsRoute
  AuthenticatedSettingsProjectsRoute: typeof AuthenticatedSettingsProjectsRouteWithChildren
  AuthenticatedSettingsPromptsRoute: typeof AuthenticatedSettingsPromptsRoute
  AuthenticatedSettingsSampleOutputsRoute: typeof AuthenticatedSettingsSampleOutputsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsAiRoute: AuthenticatedSettingsAiRoute,
  AuthenticatedSettingsAiCostsRoute: AuthenticatedSettingsAiCostsRoute,
  AuthenticatedSettingsCalendarRoute: AuthenticatedSettingsCalendarRoute,
  AuthenticatedSettingsGmailRoute: AuthenticatedSettingsGmailRoute,
  AuthenticatedSettingsHubstaffRoute: AuthenticatedSettingsHubstaffRoute,
  AuthenticatedSettingsIntegrationsRoute:
    AuthenticatedSettingsIntegrationsRoute,
  AuthenticatedSettingsLinearRoute: AuthenticatedSettingsLinearRoute,
  AuthenticatedSettingsLocationsRoute: AuthenticatedSettingsLocationsRoute,
  AuthenticatedSettingsProjectsRoute:
    AuthenticatedSettingsProjectsRouteWithChildren,
  AuthenticatedSettingsPromptsRoute: AuthenticatedSettingsPromptsRoute,
  AuthenticatedSettingsSampleOutputsRoute:
    AuthenticatedSettingsSampleOutputsRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedTodosRouteChildren {
  AuthenticatedTodosDocumentIdRoute: typeof AuthenticatedTodosDocumentIdRoute
  AuthenticatedTodosIndexRoute: typeof AuthenticatedTodosIndexRoute
}

const AuthenticatedTodosRouteChildren: AuthenticatedTodosRouteChildren = {
  AuthenticatedTodosDocumentIdRoute: AuthenticatedTodosDocumentIdRoute,
  AuthenticatedTodosIndexRoute: AuthenticatedTodosIndexRoute,
}

const AuthenticatedTodosRouteWithChildren =
  AuthenticatedTodosRoute._addFileChildren(AuthenticatedTodosRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedFocusRoute: typeof AuthenticatedFocusRoute
  AuthenticatedInboxRoute: typeof AuthenticatedInboxRoute
  AuthenticatedNotesRoute: typeof AuthenticatedNotesRouteWithChildren
  AuthenticatedPeopleRoute: typeof AuthenticatedPeopleRouteWithChildren
  AuthenticatedReflectRoute: typeof AuthenticatedReflectRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedTodayPlanRoute: typeof AuthenticatedTodayPlanRoute
  AuthenticatedTodosRoute: typeof AuthenticatedTodosRouteWithChildren
  AuthenticatedTodosListRoute: typeof AuthenticatedTodosListRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedFocusRoute: AuthenticatedFocusRoute,
  AuthenticatedInboxRoute: AuthenticatedInboxRoute,
  AuthenticatedNotesRoute: AuthenticatedNotesRouteWithChildren,
  AuthenticatedPeopleRoute: AuthenticatedPeopleRouteWithChildren,
  AuthenticatedReflectRoute: AuthenticatedReflectRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedTodayPlanRoute: AuthenticatedTodayPlanRoute,
  AuthenticatedTodosRoute: AuthenticatedTodosRouteWithChildren,
  AuthenticatedTodosListRoute: AuthenticatedTodosListRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  GmailCallbackRoute: GmailCallbackRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
